### ISSUE TITLE
ValueError when calling make

### ISSUE THREAD

**Issue by raccter** [Kyostenas/prettyTables#1]
Howdy doo. I tried using the example code provided in the readme, but got this error.

```
>>> newTable = newTable.make()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bash\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 793, in make
    windowSize = Utils.getWIndowsSize()
  File "C:\Users\bash\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 46, in getWIndowsSize
    linesIndex = mode.index(lines)+1
ValueError: 'Lines' is not in list
```

**Comment by Kyostenas** [comment]
Thank You for openning the issue. I changed the way a table is created and also updated the examples and also tested the examples on Linux and Windows :).
