### ISSUE TITLE
Autowrapping gives error sometimes.

### ISSUE THREAD

**Issue by Kyostenas** [Kyostenas/prettyTables#17]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 859, in __repr__
    return self.compose()
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1457, in compose
    rows, rows_with_i = self.__check_columns_size(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1516, in __check_columns_size
    rows, rows_with_i = self.__adjust_column_widths(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1556, in __adjust_column_widths
    auto_wrapped = self.__adjust_column_to_window(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1712, in __adjust_column_to_window
    columns = self.__wrap_or_trim_data(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1668, in __wrap_or_trim_data    columns = self.__apply_auto_wrap(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1606, in __apply_auto_wrap
    self.__auto_wrap_or_trim_headers(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\site-packages\prettyTables\table.py", line 1576, in __auto_wrap_or_trim_headers
    wrap(
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\textwrap.py", line 387, in wrap
    return w.wrap(text)
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\textwrap.py", line 362, in wrap
    return self._wrap_chunks(chunks)
  File "C:\Users\Mentalselfthink\AppData\Local\Programs\Python\Python310\lib\textwrap.py", line 256, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width 0 (must be > 0)
```

**Comment by Kyostenas** [comment]
### Done:

- 4b8d631dc9f7dbe65053e25b854dc61c7d6fbb64.
- 9d25bcc2c8d57d5cbc652e87671cf6ef86085895.
- 92e3a668fb931da0225b375d03c72f2ce9e357d0.
